version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 16

  - package-ecosystem: "cargo"
    directory: "/iso13400-2"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/iso14229-1"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/iso15765-2"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
