[workspace]
members = [
    "ecu-uds",
    "iso13400-2",
    "iso14229-1",
]

resolver = "2"

[workspace.dependencies]
#async-trait = "0.1"
#syn = { version = "2.0", features = ["full", ] }
#quote = "1.0"
#proc-macro2 = "1.0"
log = "0.4"
thiserror = "1"
lazy_static = "1"
byteorder = "1"
half = "2"
bitflags = "2"
bitfield-struct = "0.9"
derive-getters = "0"
isotp-rs = { version = "0.2.1" }
iso13400-2 = { path = "iso13400-2" }
iso14229-1 = { path = "iso14229-1" }

# dev dependencies
anyhow = "1"
hex = "0.4"
