[workspace]
members = [
    "ecu-uds",
]

resolver = "2"

[workspace.dependencies]
#async-trait = "0.1"
#syn = { version = "2.0", features = ["full", ] }
#quote = "1.0"
#proc-macro2 = "1.0"
log = "0.4"
thiserror = "1.0"
lazy_static = "1"
half = "2"
bitflags = "2"
bitfield-struct = "0.9"
isotp-rs = { version = "0.1.9" }

# dev dependencies
anyhow = "1"
hex-literal = "0.4"
